### ISSUE TITLE
不支持arm安装

### ISSUE THREAD

**Issue by wipoman** [move132/Domain-Monitoring#1]
平台：甲骨文arm。
docker安装时，出现以下告警：
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested。
docker logs如下：
exec /usr/local/bin/docker-entrypoint.sh: exec format error。
同样的配置文件，在amd平台就可以正常安装。
希望能支持arm平台，谢谢。

**Comment by move132** [comment]
已经支持

`
docker run --name=domain -itd -v $(pwd)/config.toml:/app/config.toml move132/domain-monitor:latest
`
